// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcegWc4-peHi--w9_jWPHFa5XEzs3g0Co',
    appId: '1:240679996887:web:04e3b6478bd40fd69dcf92',
    messagingSenderId: '240679996887',
    projectId: 'msu-library-app-391008',
    authDomain: 'msu-library-app-391008.firebaseapp.com',
    storageBucket: 'msu-library-app-391008.appspot.com',
    measurementId: 'G-DCWTXHKWQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8CvGLHA3hhecUwZoLq4gd08-Lh2PXJxg',
    appId: '1:240679996887:android:fd769b6cdb97a0579dcf92',
    messagingSenderId: '240679996887',
    projectId: 'msu-library-app-391008',
    storageBucket: 'msu-library-app-391008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB1r6_mBFgrX4lfJEd46S0p01NtQx39lk',
    appId: '1:240679996887:ios:ea45d005907e1dfd9dcf92',
    messagingSenderId: '240679996887',
    projectId: 'msu-library-app-391008',
    storageBucket: 'msu-library-app-391008.appspot.com',
    androidClientId: '240679996887-h7o2feh0ufr9ifeop66963j3t21avtbh.apps.googleusercontent.com',
    iosClientId: '240679996887-fac8lve116p74nasd9f87l2n36lq50r0.apps.googleusercontent.com',
    iosBundleId: 'com.msu.myLibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB1r6_mBFgrX4lfJEd46S0p01NtQx39lk',
    appId: '1:240679996887:ios:5f755b67a121edf49dcf92',
    messagingSenderId: '240679996887',
    projectId: 'msu-library-app-391008',
    storageBucket: 'msu-library-app-391008.appspot.com',
    androidClientId: '240679996887-h7o2feh0ufr9ifeop66963j3t21avtbh.apps.googleusercontent.com',
    iosClientId: '240679996887-7gvghatj9i5j5hulbat50eaqn2uvnb8g.apps.googleusercontent.com',
    iosBundleId: 'com.msu.myLibrary.RunnerTests',
  );
}
